/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia22;

import java.util.HashMap;


/**
 *
 * @author crist
 */
public class Punto3 extends javax.swing.JFrame {

    int a=1000;
    int z=0;
    int t;
    double[] e = new double[a];
    String[] p= new String[a];
    int[] c = new int[a];
    double[] A= new double[a];
    Ordenamiento Punto3=new Ordenamiento();
    
    
    public Punto3() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        per = new javax.swing.JTextField();
        cc = new javax.swing.JTextField();
        ed = new javax.swing.JTextField();
        cm = new javax.swing.JTextField();
        Botonor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PANTALLA = new javax.swing.JTextArea();
        botonper = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Met1 = new javax.swing.JComboBox<>();
        Met2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Botonor.setBackground(new java.awt.Color(102, 255, 102));
        Botonor.setText("ORDENALOS");
        Botonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonorActionPerformed(evt);
            }
        });

        PANTALLA.setColumns(20);
        PANTALLA.setRows(5);
        jScrollPane1.setViewportView(PANTALLA);

        botonper.setText("INGRESAR PERSONA");
        botonper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonperActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRE:");

        jLabel2.setText("CEDULA:");

        jLabel3.setText("EDAD:");

        jLabel4.setText("ALTURA: (cm)");

        Met1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EDAD", "ESTATURA" }));
        Met1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Met1ActionPerformed(evt);
            }
        });

        Met2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BURBUJA", "MERGERSORT" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cm, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(per, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Botonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonper, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Met2, 0, 189, Short.MAX_VALUE)
                                    .addComponent(Met1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(per, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Met2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(cm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Met1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Botonor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonper, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonorActionPerformed
          if(Met1.getSelectedItem()=="EDAD"){ 
            double[] ingreso=ing(e);  
            if(Met2.getSelectedItem()=="BURBUJA"){ 
                Punto3.burbuja(ingreso.length, ingreso);
            }else{ 
                Punto3.mergesort(ingreso, 0, ingreso.length-1);
            }
            for (int j = 0; j < z; j++) {
            liste(ingreso);
        }
        }else{
            double[] ingreso =ing(A);
            if(Met2.getSelectedItem()=="BURBUJA"){
                Punto3.burbuja(ingreso.length, ingreso); 
            }else{
                Punto3.mergesort(ingreso, 0, ingreso.length-1);
            }
            Listor(ingreso); 
        }
} 
    public double[]ing(double[] d){
        for (int j = 0; j < d.length; j++) {
            if(d[j]!=0){
                t++;
            }
        }
        double[] ingreso = new double[t];
        System.arraycopy(d, 0, ingreso, 0,t);
        return ingreso;
    

    }//GEN-LAST:event_BotonorActionPerformed

    private void botonperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonperActionPerformed
        p[z]=per.getText();
        per.setText("");
        String texto1 = cc.getText();
        c[z]=Integer.parseInt(texto1);
        cc.setText("");
        String texto2 = ed.getText();
        e[z]=Double.parseDouble(texto2);
        ed.setText("");
        String texto3 = cm.getText();
        A[z]=Double.parseDouble(texto3);
        cm.setText("");
        z++;
        org();
    }//GEN-LAST:event_botonperActionPerformed

    private void Met1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Met1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Met1ActionPerformed
 private void  org() {
        StringBuilder tex = new StringBuilder();
        for (int j = 0; j < z; j++) {
            tex.append("Persona: ").append(p[j]).append(" CC:").append(c[j]).append(" Edad: ").append(e[j]).append("Altura: ").append(A[j]).append("\n");
        }
       
    }
    private void liste(double[]ingreso){
        StringBuilder tex = new StringBuilder();
        HashMap<Double, Boolean> edad = new HashMap<>();

        for (int j = 0; j < t; j++) {
            if (!edad.containsKey(ingreso[j])) {
                for (int k = 0; k < z; k++) { 
                    if (e[k] == ingreso[j]) { 
                        tex.append("Persona: ").append(p[k]).append("Edad : ").append(e[k]).append("años\n");
                        System.out.println(e[k]); 
                    }
                }
                edad.put(ingreso[j], true);
            }
        }

        PANTALLA.setText(tex.toString());
    }
    private void Listor(double[]ingreso){
        StringBuilder tex = new StringBuilder();
        HashMap<Double, Boolean> esta = new HashMap<>();

        for (int j = 0; j < t; j++) {
            if (!esta.containsKey(ingreso[j])) {
                for (int k = 0; k < z; k++) { 
                    if (A[k] == ingreso[j]) { 
                        tex.append("Persona: ").append(p[k]).append(" Altura: ").append(A[k]).append("cm \n");
                    }
                } 
                esta.put(ingreso[j], true);
            }
        }

        PANTALLA.setText(tex.toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Punto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Punto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Punto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Punto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Punto3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botonor;
    private javax.swing.JComboBox<String> Met1;
    private javax.swing.JComboBox<String> Met2;
    private javax.swing.JTextArea PANTALLA;
    private javax.swing.JButton botonper;
    private javax.swing.JTextField cc;
    private javax.swing.JTextField cm;
    private javax.swing.JTextField ed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField per;
    // End of variables declaration//GEN-END:variables
}
